config/routes.rb
Dododr::Application.routes.draw do

  resources :spells

  resources :character_skills

  resources :character_skill_levels

  resources :parties

  resources :characters

  resources :spell_trees

  resources :attributes

  resources :skill_trees

  resources :skills

  resources :user_sessions

  resources :users

  get "login" => "user_sessions#new"
  get "logout" => "user_sessions#destroy"

  root :to => "welcome#index"

end

app/models/character_skill_level.rb
class CharacterSkillLevel < ActiveRecord::Base
  belongs_to :character
  belongs_to :skill_tree
end

app/controllers/character_skill_levels_controller.rb
class CharacterSkillLevelsController < InheritedResources::Base
end

app/views/character_skill_levels/_form.html.haml
= form_for @character_skill_level do |f|
  -if @character_skill_level.errors.any?
    #error_explanation
      %h2= "#{pluralize(@character_skill_level.errors.count, "error")} prohibited this character_skill_level from being saved:"
      %ul
        - @character_skill_level.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :character_id
    = f.text_field :character_id
  .field
    = f.label :skill_tree_id
    = f.text_field :skill_tree_id
  .field
    = f.label :level
    = f.text_field :level
  .actions
    = f.submit 'Save'

app/views/character_skill_levels/edit.html.haml
%h1 Editing character_skill_level

= render 'form'

= link_to 'Show', @character_skill_level
\|
= link_to 'Back', character_skill_levels_path

app/views/character_skill_levels/index.html.haml
%h1 Listing character_skill_levels

%table
  %tr
    %th Character
    %th Skill tree
    %th Level
    %th
    %th
    %th

  - @character_skill_levels.each do |character_skill_level|
    %tr
      %td= character_skill_level.character_id
      %td= character_skill_level.skill_tree_id
      %td= character_skill_level.level
      %td= link_to 'Show', character_skill_level
      %td= link_to 'Edit', edit_character_skill_level_path(character_skill_level)
      %td= link_to 'Destroy', character_skill_level, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Character skill level', new_character_skill_level_path

app/views/character_skill_levels/new.html.haml
%h1 New character_skill_level

= render 'form'

= link_to 'Back', character_skill_levels_path

app/views/character_skill_levels/show.html.haml
%p#notice= notice

%p
  %b Character:
  = @character_skill_level.character_id
%p
  %b Skill tree:
  = @character_skill_level.skill_tree_id
%p
  %b Level:
  = @character_skill_level.level

= link_to 'Edit', edit_character_skill_level_path(@character_skill_level)
\|
= link_to 'Back', character_skill_levels_path