config/routes.rb
Dododr::Application.routes.draw do

  resources :spells

  resources :character_skills

  resources :character_skill_levels

  resources :parties

  resources :characters

  resources :spell_trees

  resources :attributes

  resources :skill_trees

  resources :skills

  resources :user_sessions

  resources :users

  get "login" => "user_sessions#new"
  get "logout" => "user_sessions#destroy"

  root :to => "welcome#index"

end

app/models/skill_tree.rb
# -*- encoding: utf-8 -*-

class SkillTree < ActiveRecord::Base
  has_many :skills

  def class_model
    Kernel.const_get(skill_model)
  end

  def safe_name
    name.gsub(/ /,"_").gsub(/[åä]/,"a").gsub(/ö/,"o").downcase
  end

  def to_s
    name
  end
end

app/controllers/skill_trees_controller.rb
class SkillTreesController < InheritedResources::Base
end

app/views/skill_trees/_form.html.haml
= form_for @skill_tree do |f|
  -if @skill_tree.errors.any?
    #error_explanation
      %h2= "#{pluralize(@skill_tree.errors.count, "error")} prohibited this skill_tree from being saved:"
      %ul
        - @skill_tree.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :skill_model
    = f.text_field :skill_model
  .actions
    = f.submit 'Save'

app/views/skill_trees/edit.html.haml
%h1 Editing skill_tree

= render 'form'

= link_to 'Show', @skill_tree
\|
= link_to 'Back', skill_trees_path

app/views/skill_trees/index.html.haml
%h1 Listing skill_trees

%table
  %tr
    %th Name
    %th Skill model
    %th
    %th
    %th

  - @skill_trees.each do |skill_tree|
    %tr
      %td= skill_tree.name
      %td= skill_tree.skill_model
      %td= link_to 'Show', skill_tree
      %td= link_to 'Edit', edit_skill_tree_path(skill_tree)
      %td= link_to 'Destroy', skill_tree, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Skill tree', new_skill_tree_path

app/views/skill_trees/new.html.haml
%h1 New skill_tree

= render 'form'

= link_to 'Back', skill_trees_path

app/views/skill_trees/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @skill_tree.name
%p
  %b Skill model:
  = @skill_tree.skill_model

= link_to 'Edit', edit_skill_tree_path(@skill_tree)
\|
= link_to 'Back', skill_trees_path