config/routes.rb
Dododr::Application.routes.draw do

  resources :spells

  resources :character_skills

  resources :character_skill_levels

  resources :parties

  resources :characters

  resources :spell_trees

  resources :attributes

  resources :skill_trees

  resources :skills

  resources :user_sessions

  resources :users

  get "login" => "user_sessions#new"
  get "logout" => "user_sessions#destroy"

  root :to => "welcome#index"

end

app/models/character.rb
class Character < ActiveRecord::Base
  after_create :create_skills

  belongs_to :user
  belongs_to :party

  has_many :skill_levels, :class_name=>"CharacterSkillLevel"
  has_many :skills, :class_name=>"CharacterSkill"

  accepts_nested_attributes_for :skill_levels

  scope :accessible_by, lambda { |user| 
    if user.admin?
      all
    else
      find_by_user(user)
    end
  }

  def skill_level_from_text_id(text_id)
    skill_level(SkillTree.find_by_textid(text_id).id)
  end 

  def skill_level(skill_tree_id)
    csl = skill_levels.find_by_skill_tree_id(skill_tree_id)
    if csl
      csl.level
    else
      0
    end
  end

  def to_s
    name
  end
  
  def has_skill?(skill, specialization=nil)
    s = skills.find_by_skill_id(skill.id)
    if s && s.skill.specialized?
      s.specialization_id == specialization
    elsif s
      true
    else
      false
    end
  end

  def attr_value(attribute,calc_path = [], limitation=nil, base=nil) 
    Attribute.find_by_text_id(attribute).value(self,calc_path, limitation, base)
  end

  private
  def create_skills
    SkillTree.all.each do |tree|
      CharacterSkillLevel.create(:character_id=>self.id, :skill_tree_id=>tree.id, :level=>0)
    end
  end
end

app/controllers/characters_controller.rb
class CharactersController < InheritedResources::Base
end

app/views/characters/_form.html.haml
= simple_form_for @character do |f|
  -if @character.errors.any?
    #error_explanation
      %h2= "#{pluralize(@character.errors.count, "error")} prohibited this character from being saved:"
      %ul
        - @character.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.input :name
  .field
    = f.association :user
  .field
    = f.association :party

  %h4 Färdighetsvärden

  = f.simple_fields_for :skill_levels do |fs|
    .field
      = fs.input :level, :label=>fs.object.skill_tree.name, :as=>:integer
   
  .actions
    = f.submit 'Spara'

app/views/characters/edit.html.haml
%h1 Editing character

= render 'form'

= link_to 'Show', @character
\|
= link_to 'Back', characters_path

app/views/characters/index.html.haml
%h1 Listing characters

%table
  %tr
    %th Name
    %th User
    %th Party
    %th
    %th
    %th

  - @characters.each do |character|
    %tr
      %td= character.name
      %td= character.user_id
      %td= character.party_id
      %td= link_to 'Show', character
      %td= link_to 'Edit', edit_character_path(character)
      %td= link_to 'Destroy', character, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Character', new_character_path

app/views/characters/new.html.haml
%h1 New character

= render 'form'

= link_to 'Back', characters_path

app/views/characters/show.html.haml
%p#notice= notice

%h2= @character.name

%p
  = link_to 'Edit', edit_character_path(@character)
  \|
  = link_to 'Back', characters_path

%p
  %b User:
  = @character.user
%p
  %b Party:
  = @character.party


%h3= link_to "Fördjupningar:", skills_path

- @character.skill_levels.each do |slevel|
  %h4 #{slevel.skill_tree.name} (FV #{slevel.level})
  -(1..5).each do |level|
    - skills = @character.skills.level(level).skill_tree(slevel.skill_tree_id)
    - unless skills.empty?
      %h5 Nivå #{level}
      %ul
        - skills.each do |skill|
          %li= skill