config/routes.rb
Dododr::Application.routes.draw do

  resources :spells

  resources :character_skills

  resources :character_skill_levels

  resources :parties

  resources :characters

  resources :spell_trees

  resources :attributes

  resources :skill_trees

  resources :skills

  resources :user_sessions

  resources :users

  get "login" => "user_sessions#new"
  get "logout" => "user_sessions#destroy"

  root :to => "welcome#index"

end

app/models/spell_tree.rb
class SpellTree < ActiveRecord::Base
  has_many :spells

  def self.model_name
    "Vitnertavla"
  end

  def to_s
    name
  end
end

app/controllers/spell_trees_controller.rb
class SpellTreesController < InheritedResources::Base
end

app/views/spell_trees/_form.html.haml
= form_for @spell_tree do |f|
  -if @spell_tree.errors.any?
    #error_explanation
      %h2= "#{pluralize(@spell_tree.errors.count, "error")} prohibited this spell_tree from being saved:"
      %ul
        - @spell_tree.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :hvita_effect
    = f.text_field :hvita_effect
  .field
    = f.label :vaagri_effect
    = f.text_field :vaagri_effect
  .field
    = f.label :mork_effect
    = f.text_field :mork_effect
  .actions
    = f.submit 'Save'

app/views/spell_trees/edit.html.haml
%h1 Editing spell_tree

= render 'form'

= link_to 'Show', @spell_tree
\|
= link_to 'Back', spell_trees_path

app/views/spell_trees/index.html.haml
%h1 Vitnertavlor

#tree_list
  %ul
    - @spell_trees.each do |tree|
      %li
        %h3
          =link_to tree.name, '#', :class=>"toggler"
        %ul{:style=>"display: none;"}
          - tree.spells.each do |spell|
            %li
              = link_to "#{spell.level}: #{spell.name}", spell
              |
              = link_to 'Redigera', edit_spell_path(spell)

%br

= link_to 'Ny vitner', new_spell_path

:javascript
  $("a.toggler").click(function() {
    $(this.parentNode.parentNode).children("ul").toggle('fast')
    return false
  })

app/views/spell_trees/new.html.haml
%h1 New spell_tree

= render 'form'

= link_to 'Back', spell_trees_path

app/views/spell_trees/show.html.haml
%h3= @spell_tree.name

!= @spell_tree.description

%h4 Negationer
!=@spell_tree.negations

%h4 Vitner
!=@spell_tree.vitner

%p
  %b Hvitaliavitner:
  = @spell_tree.hvita_effect
%p
  %b Vaagrivitner:
  = @spell_tree.vaagri_effect
%p
  %b Morkvitalja:
  = @spell_tree.mork_effect

= link_to 'Edit', edit_spell_tree_path(@spell_tree)
\|
= link_to 'Back', spell_trees_path